services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: pet_project
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
    - 5434:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
  seq:
    container_name: seq
    image: datalust/seq
    restart: always
    environment:
    - ACCEPT_EULA=Y
    - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
    - 5341:5341
    - 8081:80
  
volumes:
  postgres-data: